### ISSUE TITLE
Source Generation in Net8.0 not working

### ISSUE THREAD

**Issue by jonmotos** [HavenDV/H.Ipc#10]
### Describe the bug

Following the simple example in the readme, no code is generated	

### Steps to reproduce the bug

New net8.0 class library, install H.Ipc, add example interface and client implementation to same source file

### Expected behavior

Code should be generated

### NuGet package version

1.0.0

### Platform

Windows Forms

### IDE

Visual Studio 2022

### Additional context

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.9.6

Errors during build:
1>CSC : warning CS8784: Generator 'HIpcGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'H.Generators.Extensions, Version=1.22.0.0, Culture=neutral, PublicKeyToken=603f13207e65c17b' or one of its dependencies. The system cannot find the file specified.'.

**Comment by bitwreckage** [comment]
I hope I am not overstepping here....

This seems to be caused by the fact that H.Ipc.Generator depends on another package called H.Generators.Extensions, and because H.Ipc/H.Ipc.Generator is an analyzer/source generator, the H.Generators.Extensions package will not be resolved at build time.
If I understand correctly, this is a [known issue](https://github.com/NuGet/Home/issues/10746) with how Nuget works. 
I have been trying all day to solve this, until my AI Assistant finally made be aware of this fact.

**Workaround**: What I have done, until I find a proper solution, is to use Nuget Package Explorer to manually add the H.Generators.Extensions.dll to the `analyzers\dotnet` folder in the `H.Ipc.nupkg` package. If you are working in a team, this approach would require that your team has its own Nuget server from which you could serve this modified version, and you would need to set up nuget Package Source Mapping so that you only fetch the (modified) H.Ipc package from your own server.

@HavenDV , maybe you have some better insight into this, and can suggest a better way to solve the issue or work around it?

I am thinking that maybe the H.Generators.Extensions project could have been brought into this repo and referenced directly by the H.Ipc project (just like the H.Ipc.Generator project is). That way we avoid the package reference, and this whole transitive package dependency issue. 

I can start working on it and issue a PR, if that would be OK with you.

**Comment by HavenDV** [comment]
Sorry you had to waste time on this. This was solved automatically before .net 8 with this file, which was delivered to the project via H.Generators.Extensions
https://github.com/HavenDV/H.Generators.Extensions/blob/main/src/libs/H.Generators.Extensions/build/H.Generators.Extensions.props
It seems that there were some changes in the .NET 8 SDK and now it does not work automatically

**Comment by HavenDV** [comment]
I've released a fix, it should be available for download in a few minutes

**Comment by bitwreckage** [comment]
Super! I've upgraded our projects to use the new version, and it seems to work fine.
I think the issue can be closed.
